title: Release Management Blog
description: Thoughts and facts on shipping quality software <br> by the team that ships Firefox every 6 to 8 weeks
extradescription: We talk here about release management at Mozilla, tooling helping decision-making, static analysis and community building around our pre-release channels.
email: release-mgmt@mozilla.com
url: "https://release.mozilla.org"
github: "https://github.com/mozilla/release-blog"
highlighter: rouge

# Navigation
navigation:
- title: Twitter
  url: https://twitter.com/MozillaReleases
- title: Team Wiki
  url: https://wiki.mozilla.org/Release_Management
- title: Release Calendar
  url: https://wiki.mozilla.org/RapidRelease/Calendar


github: {
    "hostname": "github.com",
    "pages_hostname": "github.io",
    "api_url": "https://api.github.com",
    "environment": "dotcom",
    "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
    "project_title": "Mozilla Releases",
    "project_tagline": "A page of posts both automated and manual regarding Mozilla software releases.",
    "owner_name": "mozilla",
    "owner_url": "https://github.com/mozilla",
    "repository_url": "https://github.com/mozilla/release-blog",
    "repository_nwo": "mozilla/release-blog",
    "repository_name": "release-blog",
    "zip_url": "https://github.com/mozilla/release-blog/zipball/gh-pages",
    "tar_url": "https://github.com/mozilla/release-blog/tarball/gh-pages",
    "clone_url": "https://github.com/mozilla/release-blog.git",
    "releases_url": "https://github.com/mozilla/release-blog/releases",
    "issues_url": "https://github.com/mozilla/release-blog/issues",
    "wiki_url": "https://github.com/mozilla/release-blog/wiki",
    "language": null,
    "is_user_page": false,
    "is_project_page": true,
    "show_downloads": true,
    "url": "release.mozilla.org", // (or the CNAME)
}

authors:
  calixte:
    display_name: Calixte Denizet
    gravatar: 1c26d49ffb62a4106644da39c7e6fb4c
    web: https://mozillians.org/fr/u/cdenizet/
    twitter: calixteman
    github: calixteman
  janx:
    display_name: Jan Keromnes
    gravatar: 84ed8c95500cb33a9a53038bb9e8af0e
    web: http://jan.tools/
    twitter: jankeromnes
    github: jankeromnes
  marco:
    display_name: Marco Castelluccio
    gravatar: 16d4d4a441724e006b342ac12507caef
    web: https://marco-c.github.io/
    github: marco-c
  pascal:
    display_name: Pascal Chevrel
    gravatar: 5293fe8fb106a442d842757758d07c56
    web: https://chevrel.org/
    twitter: pascalchevrel
    github: pascalchevrel

paginate: 12
excerpt_separator: "<!-- more -->"
